version: '3'

services:
  www:
    container_name: www
    image: www
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    environment:
      - API_URL=http://localhost:8000
      - API_KEY=64540a2224c7cf38dc0c696bd40da2ff
    ports:
      - 3000:3000