version: '3'

services:
  www:
    container_name: www
    image: www
    build: .
    environment:
      - API_URL=${API_URL}
      - API_KEY=${API_KEY}
    ports:
      - '3000:3000'
    command: npm run start
    restart: always

  nginx:
    build: ./nginx
    ports:
      - '80:80'
    depends_on:
      - www

