# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - alcawww

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://alcawww.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_ce61975f43d04af385597f15b0c338e5 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_bb94973fcd874a69ba378724a35a79a0 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: alcawww.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_ce61975f43d04af385597f15b0c338e5 }}/alcawww/www:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'alcawww'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_1a51949c367b496883dd6d2a76548394 }}
        images: 'alcawww.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_ce61975f43d04af385597f15b0c338e5 }}/alcawww/www:${{ github.sha }}'