
name: WWW-CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://alcawww.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_32adb98fbad146e488a58efdd37e265b }}
        password: ${{ secrets.AzureAppService_ContainerPassword_80b47a04b177438187bdb1b61700df75 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: alcawww.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_32adb98fbad146e488a58efdd37e265b }}/www:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'alcawww'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_b02748e74e2d4961b6efec5147c3b75c }}
        images: 'alcawww.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_32adb98fbad146e488a58efdd37e265b }}/www:${{ github.sha }}'